### GET request to example server
POST http://localhost:4000/api/users/create
Content-Type: application/json

{
  "userName": "iAMDk",
  "firstName": "Dilip Kumar",
  "lastName": "Yadav",
  "password": "7355228554",
  "rePassword": "7355228554",
  "email": "ydk0888@gmail.com",
  "phoneNumber": "+818095673105",
  "authorityIds": [2],
  "isActive": true
}

###